notifications:
  email: false
git:
  depth: false
  quiet: true
language: java
jdk: openjdk11
node_js: lts/*
python: 3
services: docker
install: true
addons:
  apt:
    packages:
    - curl
before_install:
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- pip install --user $(whoami) --upgrade pip >/dev/null
- $(which pip) install --user $(whoami) --upgrade httpie >/dev/null
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80
stages:
- test
- deploy
jobs:
  include:
  - stage: test
    name: docker-remote-api-app gradle-docker-plugin
    env:
    - secure: "cP0ayW1d9PzSkGAioAjbG3OXW76z9OKzGy9yNbawgGP5AMoqcYkn8Gso2VGv2gaAJRXztObd4vCksbyvqtfoVZ2yrm6auGSaGv/8GBdxdvYvAhfwkU780l0mUF9mifHO3CRkxEEq/G27SX5NR9bXZv/lrrVuYj58fqrlIggjVpkD2SZ9sqYk+DzFPZHb4aSOCTYXBdHPsM6Khlu9im+tm4aKz/IluDpfHX/L4ThDyEAXZ5xnzYvXbTtj2CQ26JQvemWSPXMrrGl9litqpK/iLZvnXPDUCbqCRtLtF3BKGzOBQ4FALPox3nKhn/uxUwlrgoD6ZrGMdb8lTclMNvKA+3DR0EX/rrpd0Nikv594U3WNz7RJpHSaxl7WibTjXOiXKWMNFM+ZSqZDy24jI1fHyhm0D18yrTzK9i+x0+xeJyUuAccRFzD2mtBjp0dy4q/PlSRWbY800aZD1QWYqwrzp/NMQgLDsJYOOegvQ+XEZwM9/io69R+WRkbTpvkOzT05CA+sX0Xm4LjOW8eiS/rC3CkA+SO5TarmmdxTq6h74wy8OXZrD2x+zRjD++6eGxO2Oy9mW6rEdxuiqBTEraLapzYNE1tAOGCofqQwgeuRj3+2ZG4VcDk9oDULxjpVUUT0c6TvjYn6uAYlfKg39vB+MTOGeyNeX1S8sfpx66TBLlk="
    script:
    - ./gradlew docker-remote-api-app:dockerBuild -Dpassword=${DOCKER_PASSWORD}
    - ./gradlew docker-remote-api-app:dockerStart
    - wait_for 8080
    - http :8080
    - http :8080/ktor/application/shutdown
    - ./gradlew docker-remote-api-app:dockerRm
    - stop_any 80 8080
  - stage: test
    name: docker-remote-api-app
    script:
    - ./gradlew clean docker-remote-api-app:installDist
    - bash docker-remote-api-app/build/install/docker-remote-api-app/bin/docker-remote-api-app &
    - wait_for 8080
    - http :8080
    - http :8080/ktor/application/shutdown
    - stop_any 80 8080
  - stage: test
    name: build
    script: ./gradlew
  - stage: deploy
    name: VuePress documentation deployment
    script: skip
    #if: branch = "master" AND type NOT IN (pull_request)
    before_deploy:
    #- if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ ".$TRAVIS_BRANCH" != ".master" ] ; then exit 0 ; fi
    - env
    - set -e
    - ./gradlew npm_i
    - ./gradlew npm_run_gh-pages
    env:
    # travis encrypt GITHUB_TOKEN=...
    - secure: "b9Q4j8w4R8VLoJn+5/1H1hhsgPo1dGB5PxP+3ZC6yy8K0mBhele9ng1LSuE9S7/9UFRjHzxG3FLdjF2FPeyRs86wO85TpOWtha9R7hLD5Kof1p/jI5fauoK2cSyJmDbRlZBdZvhlxnqwJ8iJrhXN98LXKaloHoZz5k7J2QqviYH4te+t/lM6L3tUKrbzONJtJXzPB0q0RCe+bzMWgGa2eYs0PlU6Cd+4PKHpqICZ1TaYv/FgzwJ3ZFnRgA15UyHmOq2YBlde9nnr2UjCqGlPN/nfvLSkupHoAVq6cAloMrheIYzit3VPN/k4SHW4cURxn7p6qZtmv23t7hMW0lzWKCo5zTuQnZx09NFC3OGau186yrd28jDi28Ifv3rGtjBzfZ/InsDKNPzXUF/SXGf+qvQqYJQm1X+AMcth1BPUDzU5Jw1noA7Tr47xbzo+dUTPB10YF8IADZGv57kHNe2jVdJQijehhcmPm5RYnlLx6wceMEAZ9JOCng+VOjLyOjucH9oLkkD/RevbreoUlKIzcgP8JIzlQsvhGwBcD+qPVAePJzLRkBpPrNs23R8b/xxmJsh20iben0zWlIgJCo0Gl2AU5Kf7zJCtIhdjU3ibXn9YsayYPEUMImu8nmfjZMCYF8eYp4O7g/LHogWUPDK/Ez19geX7NxN066QnZ070Aao="
    deploy: &pages
      provider: pages
      github-token: "$GITHUB_TOKEN"
      local-dir: .vuepress/dist
      # require gh-pages to be created manually first before deployment!
      target_branch: gh-pages
      skip_cleanup: true
      keep-history: true
      on:
        branch: master
        condition: "$TRAVIS_PULL_REQUEST = false"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  pip: true
  npm: true
  packages: true
  directories:
  - ./node_modules/
  - ~/.node-gyp/
  - ~/.docker/
  - ~/.gradle/
  - ~/.local/
  - ~/.npm/
