notifications:
  email: false
git:
  depth: false
  quiet: true
language: java
jdk: openjdk11
node_js: lts/*
install: true
stages:
- test
- deploy
jobs:
  include:
  - stage: test
    name: build
    script: ./gradlew
  - stage: deploy
    name: VuePress documentation deployment
    node_js: lts/*
    script: skip
    #if: branch = "master" AND type NOT IN (pull_request)
    before_deploy:
    #- if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ ".$TRAVIS_BRANCH" != ".master" ] ; then exit 0 ; fi
    - env
    - set -e
    - ./gradlew npm_i
    - ./gradlew npm_run_gh-pages
    env:
    # travis encrypt GITHUB_TOKEN=...
    - secure: "b9Q4j8w4R8VLoJn+5/1H1hhsgPo1dGB5PxP+3ZC6yy8K0mBhele9ng1LSuE9S7/9UFRjHzxG3FLdjF2FPeyRs86wO85TpOWtha9R7hLD5Kof1p/jI5fauoK2cSyJmDbRlZBdZvhlxnqwJ8iJrhXN98LXKaloHoZz5k7J2QqviYH4te+t/lM6L3tUKrbzONJtJXzPB0q0RCe+bzMWgGa2eYs0PlU6Cd+4PKHpqICZ1TaYv/FgzwJ3ZFnRgA15UyHmOq2YBlde9nnr2UjCqGlPN/nfvLSkupHoAVq6cAloMrheIYzit3VPN/k4SHW4cURxn7p6qZtmv23t7hMW0lzWKCo5zTuQnZx09NFC3OGau186yrd28jDi28Ifv3rGtjBzfZ/InsDKNPzXUF/SXGf+qvQqYJQm1X+AMcth1BPUDzU5Jw1noA7Tr47xbzo+dUTPB10YF8IADZGv57kHNe2jVdJQijehhcmPm5RYnlLx6wceMEAZ9JOCng+VOjLyOjucH9oLkkD/RevbreoUlKIzcgP8JIzlQsvhGwBcD+qPVAePJzLRkBpPrNs23R8b/xxmJsh20iben0zWlIgJCo0Gl2AU5Kf7zJCtIhdjU3ibXn9YsayYPEUMImu8nmfjZMCYF8eYp4O7g/LHogWUPDK/Ez19geX7NxN066QnZ070Aao="
    deploy: &pages
      provider: pages
      github-token: "$GITHUB_TOKEN"
      local-dir: .vuepress/dist
      # require gh-pages to be created manually first before deployment!
      target_branch: gh-pages
      skip_cleanup: true
      keep-history: true
      on:
        branch: master
        condition: "$TRAVIS_PULL_REQUEST = false"
cache:
  npm: true
  packages: true
  directories:
  - ./node_modules/
  - ~/.node-gyp/
  - ~/.npm/
